[font]
normal.family = "FiraCode Nerd Font"
bold.family = "FiraCode Nerd Font"
italic.family = "FiraCode Nerd Font"
bold_italic.family = "FiraCode Nerd Font"

# for "normal" using
# size = 14.0

# for another "keybord" using
size = 14.0
