# theme = "pop-dark"
theme = "vim_dark_high_contrast"
# theme = "ashen"

[editor]
color-modes = true
true-color = true
auto-pairs = true

[keys.insert]
esc = ["collapse_selection", "normal_mode"]

[keys.normal]
esc = ["collapse_selection", ":w"]
ret = ["move_line_down", "goto_first_nonwhitespace"]

[editor.file-picker]
hidden = true
git-ignore = true

[editor.lsp]
display-messages = true

[keys.select]
esc = ["collapse_selection", "keep_primary_selection", "normal_mode"]
0   = "goto_line_start"
